// Admin Service Firebase Interface
export {
  adminServiceCanister,
  assignRole,
  removeRole,
  getUserRole,
  checkAdminRole,
  listUserRoles,
  hasAdminRole,
  getSystemStats,
  getAllUsers,
  getBookingsData,
  getUserServicesAndBookings,
  getUserServiceCount,
  lockUserAccount,
  getAllUserLockStatuses,
  updateUserReputation,
  updateCertificateValidationStatus,
  getValidatedCertificates,
  getRejectedCertificates,
  getReportsFromFeedbackCanister,
  getFeedbackStats,
  getAllFeedback,
  updateReportStatus,
  sendTicketCommentNotificationToUser,
  updateAdminActor,
} from "./index";
export * from "./serviceTypes";
